### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by netcookies**
1. add exception for get_txt_records
2. add exit_hook for latest version of dehydrated
3. Project name change from letsencrypt.sh to dehydrated

### CODE REVIEW

**Comment by ftao** [comment]
I think  the change from "letsencrypt.sh ' to  'dehydrated'  is not fit for this repo ..

**Comment by netcookies** [comment]
For what reason? 
FYI: I have test it with dehydrated

**Comment by ftao** [comment]
Sorry , I does not realize the the name changed by the author .. 
I thought it is some kind of fork ..

**Comment by netcookies** [comment]
May be u want to change name either :) haha,   thanks for the merge

**Pull request merged**
